services:
  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - fullstack-network
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - fullstack-network
    restart: unless-stopped

networks:
  fullstack-network:
    driver: bridge

